// Generated from assets/audio/manifest.json (tools/audio/files.js). Do not edit.

export const SFX_FILES: Record<string, number> = {
  "error": require("../../assets/audio/sfx_error.m4a"),
  "shards": require("../../assets/audio/sfx_shards.m4a"),
  "locked": require("../../assets/audio/sfx_locked.m4a"),
  "manipulate_nuit": require("../../assets/audio/sfx_manipulate_nuit.m4a"),
  "manipulate_phare": require("../../assets/audio/sfx_manipulate_phare.m4a"),
  "manipulate_horlo": require("../../assets/audio/sfx_manipulate_horlo.m4a"),
  "manipulate_marche": require("../../assets/audio/sfx_manipulate_marche.m4a"),
  "manipulate_serre": require("../../assets/audio/sfx_manipulate_serre.m4a"),
  "lanternLit_nuit": require("../../assets/audio/sfx_lanternLit_nuit.m4a"),
  "lanternLit_phare": require("../../assets/audio/sfx_lanternLit_phare.m4a"),
  "lanternLit_horlo": require("../../assets/audio/sfx_lanternLit_horlo.m4a"),
  "lanternLit_marche": require("../../assets/audio/sfx_lanternLit_marche.m4a"),
  "lanternLit_serre": require("../../assets/audio/sfx_lanternLit_serre.m4a"),
  "roomComplete_nuit": require("../../assets/audio/sfx_roomComplete_nuit.m4a"),
  "roomComplete_phare": require("../../assets/audio/sfx_roomComplete_phare.m4a"),
  "roomComplete_horlo": require("../../assets/audio/sfx_roomComplete_horlo.m4a"),
  "roomComplete_marche": require("../../assets/audio/sfx_roomComplete_marche.m4a"),
  "roomComplete_serre": require("../../assets/audio/sfx_roomComplete_serre.m4a"),
  "unlock_nuit": require("../../assets/audio/sfx_unlock_nuit.m4a"),
  "unlock_phare": require("../../assets/audio/sfx_unlock_phare.m4a"),
  "unlock_horlo": require("../../assets/audio/sfx_unlock_horlo.m4a"),
  "unlock_marche": require("../../assets/audio/sfx_unlock_marche.m4a"),
  "unlock_serre": require("../../assets/audio/sfx_unlock_serre.m4a"),
  "newDistrict_nuit": require("../../assets/audio/sfx_newDistrict_nuit.m4a"),
  "newDistrict_phare": require("../../assets/audio/sfx_newDistrict_phare.m4a"),
  "newDistrict_horlo": require("../../assets/audio/sfx_newDistrict_horlo.m4a"),
  "newDistrict_marche": require("../../assets/audio/sfx_newDistrict_marche.m4a"),
  "newDistrict_serre": require("../../assets/audio/sfx_newDistrict_serre.m4a"),
  "hint_nuit": require("../../assets/audio/sfx_hint_nuit.m4a"),
  "hint_phare": require("../../assets/audio/sfx_hint_phare.m4a"),
  "hint_horlo": require("../../assets/audio/sfx_hint_horlo.m4a"),
  "hint_marche": require("../../assets/audio/sfx_hint_marche.m4a"),
  "hint_serre": require("../../assets/audio/sfx_hint_serre.m4a"),
  "bell_0": require("../../assets/audio/sfx_bell_0.m4a"),
  "bell_1": require("../../assets/audio/sfx_bell_1.m4a"),
  "bell_2": require("../../assets/audio/sfx_bell_2.m4a"),
  "bell_3": require("../../assets/audio/sfx_bell_3.m4a"),
  "bell_4": require("../../assets/audio/sfx_bell_4.m4a"),
  "bell_5": require("../../assets/audio/sfx_bell_5.m4a"),
  "manipulate_biblio": require("../../assets/audio/sfx_manipulate_biblio.m4a"),
  "manipulate_theatre": require("../../assets/audio/sfx_manipulate_theatre.m4a"),
  "manipulate_obs": require("../../assets/audio/sfx_manipulate_obs.m4a"),
  "lanternLit_biblio": require("../../assets/audio/sfx_lanternLit_biblio.m4a"),
  "lanternLit_theatre": require("../../assets/audio/sfx_lanternLit_theatre.m4a"),
  "lanternLit_obs": require("../../assets/audio/sfx_lanternLit_obs.m4a"),
  "roomComplete_biblio": require("../../assets/audio/sfx_roomComplete_biblio.m4a"),
  "roomComplete_theatre": require("../../assets/audio/sfx_roomComplete_theatre.m4a"),
  "roomComplete_obs": require("../../assets/audio/sfx_roomComplete_obs.m4a"),
  "unlock_biblio": require("../../assets/audio/sfx_unlock_biblio.m4a"),
  "unlock_theatre": require("../../assets/audio/sfx_unlock_theatre.m4a"),
  "unlock_obs": require("../../assets/audio/sfx_unlock_obs.m4a"),
  "newDistrict_biblio": require("../../assets/audio/sfx_newDistrict_biblio.m4a"),
  "newDistrict_theatre": require("../../assets/audio/sfx_newDistrict_theatre.m4a"),
  "newDistrict_obs": require("../../assets/audio/sfx_newDistrict_obs.m4a"),
  "hint_biblio": require("../../assets/audio/sfx_hint_biblio.m4a"),
  "hint_theatre": require("../../assets/audio/sfx_hint_theatre.m4a"),
  "hint_obs": require("../../assets/audio/sfx_hint_obs.m4a"),
  "bell_xylo_0": require("../../assets/audio/sfx_bell_xylo_0.m4a"),
  "bell_harp_0": require("../../assets/audio/sfx_bell_harp_0.m4a"),
  "bell_xylo_1": require("../../assets/audio/sfx_bell_xylo_1.m4a"),
  "bell_harp_1": require("../../assets/audio/sfx_bell_harp_1.m4a"),
  "bell_xylo_2": require("../../assets/audio/sfx_bell_xylo_2.m4a"),
  "bell_harp_2": require("../../assets/audio/sfx_bell_harp_2.m4a"),
  "bell_xylo_3": require("../../assets/audio/sfx_bell_xylo_3.m4a"),
  "bell_harp_3": require("../../assets/audio/sfx_bell_harp_3.m4a"),
  "bell_xylo_4": require("../../assets/audio/sfx_bell_xylo_4.m4a"),
  "bell_harp_4": require("../../assets/audio/sfx_bell_harp_4.m4a"),
  "bell_xylo_5": require("../../assets/audio/sfx_bell_xylo_5.m4a"),
  "bell_harp_5": require("../../assets/audio/sfx_bell_harp_5.m4a"),
};
export const AMBIENCE_FILES: Record<string, number> = {
  "nuit": require("../../assets/audio/amb_nuit.m4a"),
  "phare": require("../../assets/audio/amb_phare.m4a"),
  "horlo": require("../../assets/audio/amb_horlo.m4a"),
  "marche": require("../../assets/audio/amb_marche.m4a"),
  "serre": require("../../assets/audio/amb_serre.m4a"),
  "biblio": require("../../assets/audio/amb_biblio.m4a"),
  "theatre": require("../../assets/audio/amb_theatre.m4a"),
  "obs": require("../../assets/audio/amb_obs.m4a"),
};
export const AMBIENCE_LOOP_SECONDS = 48;
export const AMBIENCE_OVERLAP_SECONDS = 4;
